Write a function to create a numpy array using only the input: start, length, and stop.
Use the function to create an numpy array of length 100, starting from 6 and has a step of 4 between consecutive numbers

In [82]:
def get_numpy_arr(start,length,stop):
    return np.arange(start=start, stop=stop, step=(stop-start)/length,dtype=int)

print(get_numpy_arr(start=6,length=100,stop=406))
print(len(get_numpy_arr(start=6,length=100,stop=406)))

[  6  10  14  18  22  26  30  34  38  42  46  50  54  58  62  66  70  74
  78  82  86  90  94  98 102 106 110 114 118 122 126 130 134 138 142 146
 150 154 158 162 166 170 174 178 182 186 190 194 198 202 206 210 214 218
 222 226 230 234 238 242 246 250 254 258 262 266 270 274 278 282 286 290
 294 298 302 306 310 314 318 322 326 330 334 338 342 346 350 354 358 362
 366 370 374 378 382 386 390 394 398 402]
100


2.Drop all nan values from the following numpy array.



In [81]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
no_nans_a = np.array(list(filter(lambda x: np.isfinite(x), a))).astype(int)
no_nans_a = np.array([num for num in a if  np.isfinite(num)]).astype(int)
print(no_nans_a)

[1 2 3 5 6 7]


create a random numpy array that has a shape of (5, 6) filled with integers between 1 and 100.
Then compute the maximum int for each row in the array




In [97]:
x = np.random.randint(1, 101, size=(5,6))
print(x)
row_maximums = np.amax(x,1)
print(row_maximums)

[[72 89 24 41 63 91]
 [65 71 47 29 50 54]
 [86 56 37 58 62 94]
 [45 69 66 85 83 96]
 [26 46 96 78 77  1]]
[91 71 94 96 96]


4.
use a pandas Series function to find the unique values and their frequencies of the following Series:

series = pd.Series(np.take(list('abcdefghijklmnop'), np.random.randint(16, size=500)))